import primszam


primszam.prim2(1)
print("1. teszteset")
print("5. print")
print()
primszam.prim2(5)
print("2. teszteset")
print("nem prím")
print()
primszam.prim2(6)
print("3. teszteset")
print("a szám nem prím szám")
primszam.prim2(0)
print("4. teszteset")
print("a szám nem prím szám")
print()
primszam.prim2(2)
print("5. teszteset")
print("a szám prím szám")
print()
primszam.prim2(-3)
print("6. teszteset")
print("a szám nem prím szám")
print()
